# Generated by Django 2.2.6 on 2019-10-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['recruit'], 'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='planet',
            options={'ordering': ['name'], 'verbose_name': 'Планета', 'verbose_name_plural': 'Планеты'},
        ),
        migrations.AddField(
            model_name='recruit',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Прошел тест'),
        ),
    ]
